#! /bin/sh

bspc config border_width                1
bspc config window_gap                  12

bspc config split_ratio                  0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     true
bspc config focus_follows_pointer       true

xrandr --output eDP-1 --auto
bspc monitor eDP-1 -d 1 2 3 4 5 6

bspc rule -a spotify state=pseudo_tiled
bspc rule -a zathura state=tiled
