library: ~/Sync/Music/Beets/library.db
directory: ~/Sync/Music/Beets
paths:
     default: $artist/$album%aunique{}/$title
     singleton: $artist/Singles/$title
asciify_paths: yes

plugins: info duplicates fromfilename scrub ftintitle fetchart embedart

scrub:
    auto: yes

fetchart:
    sources: coverart itunes amazon albumart wikipedia google
